settings:
  title: 'andrewnet status'
  url: 'https://status.andrewnet.net' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: andrewnet # unique identifier
    name: andrewnet.net
    description: 'main andrewnet website running on pages' # default=empty
    url: 'https://www.andrewnet.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: adfs
    name: andrewnet authentication 
    description: 'main auth system for andrewnet running on adfs at 186'
    url: 'https://adfs.andrewnet.net/adfs/ls/idpinitiatedsignon'
    method: GET
    expectStatus: 200

  - id: nextcloud
    name: nextcloud
    description: 'main file access andrewnet located at 186'
    url: 'https://nxtc.andrewnet.net/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    
  - id: cloudhub # unique identifier
    name: cloud hub
    description: 'the andrewnet cloud hub running on pages' # default=empty
    url: 'https://hub.andrewnet.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: cdn # unique identifier
    name: andrewnet cloud cdn
    description: 'andrewnet main cloud content delivery network running on render' # default=empty
    url: 'https://cloud.cdn.andrewnet.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 304 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    
  - id: njit # unique identifier
    name: andrewnet njit website
    description: 'andrewnet njit website running at njit' # default=empty
    url: 'https://web.njit.edu/~aja9/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
