settings:
  title: 'andrewnet status'
  url: 'https://status.andrewnet.net' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: andrewnet # unique identifier
    name: andrewnet.net
    description: 'main andrewnet website' # default=empty
    url: 'https://www.andrewnet.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: adfs
    name: andrewnet authentication 
    description: 'main auth system for andrewnet running on adfs'
    url: 'https://adfs.andrewnet.net/adfs/ls/idpinitiatedsignon'
    method: GET
    expectStatus: 200

  - id: nextcloud
    name: nextcloud
    url: 'https://nxtc.andrewnet.net/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    
  - id: cloudhub # unique identifier
    name: cloud hub
    description: 'the andrewnet cloud hub running on netlify' # default=empty
    url: 'https://hub.andrewnet.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
